v=0;
m=600;
i=1;
sd=1;
simOut = sim('untitled.mdl');
dt = 0.002;
t = x(:,1) - x(1,1);
sig = x(:,2);
sig = sig(end-4095:end);
sig = detrend(sig);
f = fft(sig);
freqs = (0:(length(f)/2)-1)*1/length(f)/dt;
f2 = f(1:(length(f)/2));
f2 = f2*2/length(t);
[max_val,ind] = max(abs(f2).^2);
peaks(i) = freqs(ind);
peak_vals(i) = max_val;
i=i+1;
figure;
plot(freqs,abs(f2).^2);
semilogy(freqs,abs(f2).^2);
plot(dt*1:length(sig),sig);